services:
  - type: web
    name: linktree-clone
    runtime: node
    repo: https://github.com/zubkovtima-creator/linktree-clone
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: FRONTEND_URL
        value: https://linktree-clone-g7ta.onrender.com
